name: live_photos
description: This generates LivePhotos which is a feature to be able to use in only iOS from video url and it's downloaded to Camera Roll.
version: 0.2.0
homepage: 'https://github.com/YuheiNakasaka/flutter_live_photos'

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: LivePhotosPlugin
