name: live_photos
description: A flutter plugin to generate LivePhotos.
version: 0.0.1
homepage: 'https://github.com/YuheiNakasaka/flutter_live_photos'

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: LivePhotosPlugin
